import { QuizStep } from '@/types';

// Comprehensive fragrance notes organized by category (11 categories, 198 notes)
export const fragranceNotes = {
    freshCitrus: [
        { id: 'bergamot', label: 'Bergamot', labelAr: 'برغموت', icon: 'bergamot' },
        { id: 'lemon', label: 'Lemon', labelAr: 'ليمون', icon: 'lemon' },
        { id: 'lime', label: 'Lime', labelAr: 'ليمون أخضر', icon: 'lime' },
        { id: 'grapefruit', label: 'Grapefruit', labelAr: 'جريب فروت', icon: 'grapefruit' },
        { id: 'mandarin', label: 'Mandarin', labelAr: 'يوسفي', icon: 'mandarin' },
        { id: 'tangerine', label: 'Tangerine', labelAr: 'تانجرين', icon: 'mandarin' },
        { id: 'blood-orange', label: 'Blood Orange', labelAr: 'برتقال دموي', icon: 'blood-orange' },
        { id: 'blood-mandarin', label: 'Blood Mandarin', labelAr: 'يوسفي دموي', icon: 'mandarin' },
        { id: 'citron', label: 'Citron', labelAr: 'سيترون', icon: 'citron' },
        { id: 'amalfi-lemon', label: 'Amalfi Lemon', labelAr: 'ليمون أمالفي', icon: 'lemon' },
        { id: 'calabrian-bergamot', label: 'Calabrian Bergamot', labelAr: 'برغموت قلوري', icon: 'bergamot' },
        { id: 'sicilian-orange', label: 'Sicilian Orange', labelAr: 'برتقال صقلي', icon: 'blood-orange' },
        { id: 'italian-lemon', label: 'Italian Lemon', labelAr: 'ليمون إيطالي', icon: 'lemon' },
        { id: 'red-mandarin', label: 'Red Mandarin', labelAr: 'يوسفي أحمر', icon: 'mandarin' },
        { id: 'mandarin-orange', label: 'Mandarin Orange', labelAr: 'يوسفي برتقالي', icon: 'mandarin' },
        { id: 'mandarin-blossom', label: 'Mandarin Blossom', labelAr: 'زهر اليوسفي', icon: 'blossom' },
        { id: 'bitter-orange', label: 'Bitter Orange', labelAr: 'برتقال مر', icon: 'blood-orange' },
        { id: 'frozen-apple', label: 'Frozen Apple', labelAr: 'تفاح مجمد', icon: 'apple' },
        { id: 'peppermint', label: 'Peppermint', labelAr: 'نعناع فلفلي', icon: 'mint' },
        { id: 'mint', label: 'Mint', labelAr: 'نعناع', icon: 'mint' },
        { id: 'petitgrain', label: 'Petitgrain', labelAr: 'بيتي جران', icon: 'leaf' },
        { id: 'aldehydes', label: 'Aldehydes', labelAr: 'ألديهايد', icon: 'sparkle' },
        { id: 'lime-oil', label: 'Lime Oil', labelAr: 'زيت ليمون', icon: 'lime' },
        { id: 'marine-notes', label: 'Marine Notes', labelAr: 'نوتات بحرية', icon: 'wave' },
        { id: 'calone', label: 'Calone', labelAr: 'كالون', icon: 'wave' },
        { id: 'aqueous', label: 'Aqueous', labelAr: 'مائي', icon: 'wave' },
        { id: 'litsea-cubeba', label: 'Litsea Cubeba', labelAr: 'ليتسيا كوبيبا', icon: 'lemon' },
    ],
    floral: [
        { id: 'rose', label: 'Rose', labelAr: 'ورد', icon: 'rose' },
        { id: 'jasmine', label: 'Jasmine', labelAr: 'ياسمين', icon: 'jasmine' },
        { id: 'orange-blossom', label: 'Orange Blossom', labelAr: 'زهر البرتقال', icon: 'blossom' },
        { id: 'ylang', label: 'Ylang-Ylang', labelAr: 'يلانج يلانج', icon: 'ylang' },
        { id: 'orchid', label: 'Orchid', labelAr: 'أوركيد', icon: 'orchid' },
        { id: 'lily-valley', label: 'Lily of the Valley', labelAr: 'زنبق الوادي', icon: 'lily' },
        { id: 'tuberose', label: 'Tuberose', labelAr: 'تيوبروز', icon: 'tuberose' },
        { id: 'peony', label: 'Peony', labelAr: 'فاوانيا', icon: 'peony' },
        { id: 'freesia', label: 'Freesia', labelAr: 'فريزيا', icon: 'freesia' },
        { id: 'gardenia', label: 'Gardenia', labelAr: 'غاردينيا', icon: 'gardenia' },
        { id: 'magnolia', label: 'Magnolia', labelAr: 'ماغنوليا', icon: 'magnolia' },
        { id: 'iris', label: 'Iris/Orris', labelAr: 'سوسن', icon: 'iris' },
        { id: 'heliotrope', label: 'Heliotrope', labelAr: 'هليوتروب', icon: 'heliotrope' },
        { id: 'carnation', label: 'Carnation', labelAr: 'قرنفل زهري', icon: 'carnation' },
        { id: 'turkish-rose', label: 'Turkish Rose', labelAr: 'ورد تركي', icon: 'rose' },
        { id: 'bulgarian-rose', label: 'Bulgarian Rose', labelAr: 'ورد بلغاري', icon: 'rose' },
        { id: 'may-rose', label: 'May Rose', labelAr: 'ورد ماي', icon: 'rose' },
        { id: 'pink-lotus', label: 'Pink Lotus', labelAr: 'لوتس وردي', icon: 'lotus' },
        { id: 'violet', label: 'Violet', labelAr: 'بنفسج', icon: 'violet' },
        { id: 'african-orange-flower', label: 'African Orange Flower', labelAr: 'زهر البرتقال الأفريقي', icon: 'blossom' },
        { id: 'geranium', label: 'Geranium', labelAr: 'إبرة الراعي', icon: 'geranium' },
        { id: 'reseda', label: 'Reseda', labelAr: 'ريسيدا', icon: 'reseda' },
        { id: 'cyclamen', label: 'Cyclamen', labelAr: 'سيكلامن', icon: 'cyclamen' },
        { id: 'lily', label: 'Lily', labelAr: 'زنبق', icon: 'lily' },
        { id: 'solar-notes', label: 'Solar Notes', labelAr: 'نوتات شمسية', icon: 'sun' },
        { id: 'honeysuckle', label: 'Honeysuckle', labelAr: 'زهر العسل', icon: 'honeysuckle' },
        { id: 'pink-jasmine', label: 'Pink Jasmine', labelAr: 'ياسمين وردي', icon: 'jasmine' },
        { id: 'pomarose', label: 'Pomarose', labelAr: 'بوماروز', icon: 'blossom' },
        { id: 'hedione', label: 'Hedione', labelAr: 'هيديون', icon: 'sparkle' },
        { id: 'neroli', label: 'Neroli', labelAr: 'نيرولي', icon: 'blossom' },
        { id: 'hyacinth', label: 'Hyacinth', labelAr: 'سنبل', icon: 'hyacinth' },
        { id: 'white-flowers', label: 'White Flowers', labelAr: 'زهور بيضاء', icon: 'gardenia' },
        { id: 'muguet', label: 'Muguet', labelAr: 'موجيه', icon: 'lily' },
    ],
    sweetGourmand: [
        { id: 'vanilla', label: 'Vanilla', labelAr: 'فانيليا', icon: 'vanilla' },
        { id: 'chocolate', label: 'Chocolate', labelAr: 'شوكولاتة', icon: 'chocolate' },
        { id: 'caramel', label: 'Caramel', labelAr: 'كراميل', icon: 'caramel' },
        { id: 'praline', label: 'Praline', labelAr: 'برالين', icon: 'praline' },
        { id: 'honey', label: 'Honey', labelAr: 'عسل', icon: 'honey' },
        { id: 'coffee', label: 'Coffee', labelAr: 'قهوة', icon: 'coffee' },
        { id: 'sugar', label: 'Sugar', labelAr: 'سكر', icon: 'sugar' },
        { id: 'marshmallow', label: 'Marshmallow', labelAr: 'مارشميلو', icon: 'marshmallow' },
        { id: 'chestnut', label: 'Chestnut', labelAr: 'كستناء', icon: 'chestnut' },
        { id: 'truffle', label: 'Truffle', labelAr: 'كمأة', icon: 'truffle' },
        { id: 'hazelnut', label: 'Hazelnut', labelAr: 'بندق', icon: 'hazelnut' },
        { id: 'cocoa-butter', label: 'Cocoa Butter', labelAr: 'زبدة الكاكاو', icon: 'chocolate' },
        { id: 'coconut-milk', label: 'Coconut Milk', labelAr: 'حليب جوز الهند', icon: 'coconut' },
        { id: 'whipped-cream', label: 'Whipped Cream', labelAr: 'كريمة مخفوقة', icon: 'cream' },
        { id: 'cookie', label: 'Cookie', labelAr: 'كوكيز', icon: 'cookie' },
        { id: 'waffle', label: 'Waffle', labelAr: 'وافل', icon: 'waffle' },
        { id: 'toffee', label: 'Toffee', labelAr: 'توفي', icon: 'toffee' },
        { id: 'hazelnut-milk', label: 'Hazelnut Milk', labelAr: 'حليب البندق', icon: 'hazelnut' },
        { id: 'rum', label: 'Rum', labelAr: 'روم', icon: 'rum' },
        { id: 'banana-cream', label: 'Banana Cream', labelAr: 'كريمة الموز', icon: 'cream' },
        { id: 'biscuit', label: 'Biscuit', labelAr: 'بسكويت', icon: 'biscuit' },
        { id: 'milk', label: 'Milk', labelAr: 'حليب', icon: 'milk' },
        { id: 'sugar-cane', label: 'Sugar Cane', labelAr: 'قصب السكر', icon: 'sugar' },
        { id: 'cognac', label: 'Cognac', labelAr: 'كونياك', icon: 'cognac' },
        { id: 'dried-fruits', label: 'Dried Fruits', labelAr: 'فواكه مجففة', icon: 'dried-fruits' },
        { id: 'licorice', label: 'Licorice', labelAr: 'عرق سوس', icon: 'licorice' },
        { id: 'caramelized-popcorn', label: 'Caramelized Popcorn', labelAr: 'فشار بالكراميل', icon: 'caramel' },
        { id: 'mexican-chocolate', label: 'Mexican Chocolate', labelAr: 'شوكولاتة مكسيكية', icon: 'chocolate' },
        { id: 'cacao', label: 'Cacao', labelAr: 'كاكاو', icon: 'chocolate' },
        { id: 'coumarin', label: 'Coumarin', labelAr: 'كومارين', icon: 'coumarin' },
        { id: 'bitter-almond', label: 'Bitter Almond', labelAr: 'لوز مر', icon: 'almond' },
        { id: 'nuts', label: 'Nuts', labelAr: 'مكسرات', icon: 'hazelnut' },
    ],
    woody: [
        { id: 'cedar', label: 'Cedar', labelAr: 'أرز', icon: 'cedar' },
        { id: 'sandalwood', label: 'Sandalwood', labelAr: 'صندل', icon: 'sandalwood' },
        { id: 'patchouli', label: 'Patchouli', labelAr: 'باتشولي', icon: 'patchouli' },
        { id: 'vetiver', label: 'Vetiver', labelAr: 'فيتيفر', icon: 'vetiver' },
        { id: 'guaiac', label: 'Guaiac Wood', labelAr: 'خشب الغاياك', icon: 'guaiac' },
        { id: 'amberwood', label: 'Amberwood', labelAr: 'خشب العنبر', icon: 'amberwood' },
        { id: 'cashmere-wood', label: 'Cashmere Wood', labelAr: 'خشب الكشمير', icon: 'cashmere-wood' },
        { id: 'virginian-cedarwood', label: 'Virginian Cedarwood', labelAr: 'أرز فرجيني', icon: 'cedar' },
        { id: 'ebony', label: 'Ebony', labelAr: 'أبنوس', icon: 'ebony' },
        { id: 'cypriol', label: 'Cypriol', labelAr: 'سيبريول', icon: 'cypriol' },
        { id: 'oakwood', label: 'Oakwood', labelAr: 'خشب البلوط', icon: 'oakwood' },
        { id: 'akigalawood', label: 'Akigalawood', labelAr: 'أكيغالاوود', icon: 'akigalawood' },
        { id: 'birch', label: 'Birch', labelAr: 'بتولا', icon: 'birch' },
        { id: 'oakmoss', label: 'Oakmoss', labelAr: 'طحلب البلوط', icon: 'oakmoss' },
    ],
    spicy: [
        { id: 'cinnamon', label: 'Cinnamon', labelAr: 'قرفة', icon: 'cinnamon' },
        { id: 'cardamom', label: 'Cardamom', labelAr: 'هيل', icon: 'cardamom' },
        { id: 'pink-pepper', label: 'Pink Pepper', labelAr: 'فلفل وردي', icon: 'pink-pepper' },
        { id: 'black-pepper', label: 'Black Pepper', labelAr: 'فلفل أسود', icon: 'black-pepper' },
        { id: 'ginger', label: 'Ginger', labelAr: 'زنجبيل', icon: 'ginger' },
        { id: 'nutmeg', label: 'Nutmeg', labelAr: 'جوزة الطيب', icon: 'nutmeg' },
        { id: 'saffron', label: 'Saffron', labelAr: 'زعفران', icon: 'saffron' },
        { id: 'clove', label: 'Clove', labelAr: 'قرنفل', icon: 'clove' },
        { id: 'cumin', label: 'Cumin', labelAr: 'كمون', icon: 'cumin' },
        { id: 'caraway', label: 'Caraway', labelAr: 'كراوية', icon: 'caraway' },
        { id: 'red-pepper', label: 'Red Pepper', labelAr: 'فلفل أحمر', icon: 'red-pepper' },
        { id: 'bell-pepper', label: 'Bell Pepper', labelAr: 'فلفل رومي', icon: 'bell-pepper' },
        { id: 'star-anise', label: 'Star Anise', labelAr: 'يانسون نجمي', icon: 'star-anise' },
        { id: 'ceylon-cinnamon', label: 'Ceylon Cinnamon', labelAr: 'قرفة سيلانية', icon: 'cinnamon' },
        { id: 'fresh-ginger', label: 'Fresh Ginger', labelAr: 'زنجبيل طازج', icon: 'ginger' },
        { id: 'allspice', label: 'Allspice', labelAr: 'بهار حلو', icon: 'allspice' },
    ],
    amberyResinous: [
        { id: 'amber', label: 'Amber', labelAr: 'عنبر', icon: 'amber' },
        { id: 'ambroxan', label: 'Ambroxan', labelAr: 'أمبروكسان', icon: 'ambroxan' },
        { id: 'benzoin', label: 'Benzoin', labelAr: 'بنزوين', icon: 'benzoin' },
        { id: 'olibanum', label: 'Olibanum (Frankincense)', labelAr: 'لبان ذكر', icon: 'frankincense' },
        { id: 'incense', label: 'Incense', labelAr: 'بخور', icon: 'incense' },
        { id: 'tonka', label: 'Tonka Bean', labelAr: 'تونكا', icon: 'tonka' },
        { id: 'grey-amber', label: 'Grey Amber', labelAr: 'عنبر رمادي', icon: 'amber' },
        { id: 'ambergris', label: 'Ambergris', labelAr: 'عنبر حوتي', icon: 'ambergris' },
        { id: 'myrrh', label: 'Myrrh', labelAr: 'مر', icon: 'myrrh' },
        { id: 'tolu-balsam', label: 'Tolu Balsam', labelAr: 'بلسم تولو', icon: 'balsam' },
        { id: 'styrax', label: 'Styrax', labelAr: 'ستيراكس', icon: 'styrax' },
        { id: 'cistus', label: 'Cistus', labelAr: 'سيستوس', icon: 'cistus' },
        { id: 'beeswax', label: 'Beeswax', labelAr: 'شمع النحل', icon: 'beeswax' },
        { id: 'labdanum', label: 'Labdanum', labelAr: 'لابدانوم', icon: 'labdanum' },
        { id: 'elemi', label: 'Elemi', labelAr: 'إيليمي', icon: 'elemi' },
    ],
    musky: [
        { id: 'musk', label: 'Musk', labelAr: 'مسك', icon: 'musk' },
        { id: 'white-musk', label: 'White Musk', labelAr: 'مسك أبيض', icon: 'white-musk' },
        { id: 'black-musk', label: 'Black Musk', labelAr: 'مسك أسود', icon: 'black-musk' },
        { id: 'ambrette', label: 'Ambrette', labelAr: 'أمبريت', icon: 'ambrette' },
        { id: 'cashmeran', label: 'Cashmeran', labelAr: 'كشميران', icon: 'cashmeran' },
    ],
    leatherSmoky: [
        { id: 'leather', label: 'Leather', labelAr: 'جلد', icon: 'leather' },
        { id: 'smoke', label: 'Smoke', labelAr: 'دخان', icon: 'smoke' },
        { id: 'tobacco', label: 'Tobacco', labelAr: 'تبغ', icon: 'tobacco' },
        { id: 'suede', label: 'Suede', labelAr: 'شمواه', icon: 'suede' },
        { id: 'whiskey', label: 'Whiskey', labelAr: 'ويسكي', icon: 'whiskey' },
        { id: 'whisky-absolute', label: 'Whisky Absolute', labelAr: 'ويسكي مطلق', icon: 'whiskey' },
        { id: 'cannabis', label: 'Cannabis', labelAr: 'قنب هندي', icon: 'cannabis' },
        { id: 'birch-tar', label: 'Birch Tar', labelAr: 'قطران البتولا', icon: 'birch-tar' },
    ],
    earthyGreen: [
        { id: 'basil', label: 'Basil', labelAr: 'ريحان', icon: 'basil' },
        { id: 'sage', label: 'Sage', labelAr: 'ميرمية', icon: 'sage' },
        { id: 'clary-sage', label: 'Clary Sage', labelAr: 'ميرمية ضمية', icon: 'clary-sage' },
        { id: 'rosemary', label: 'Rosemary', labelAr: 'إكليل الجبل', icon: 'rosemary' },
        { id: 'lavender', label: 'Lavender', labelAr: 'لافندر', icon: 'lavender' },
        { id: 'cypress', label: 'Cypress', labelAr: 'سرو', icon: 'cypress' },
        { id: 'juniper', label: 'Juniper Berries', labelAr: 'عرعر', icon: 'juniper' },
        { id: 'seaweed', label: 'Seaweed', labelAr: 'أعشاب بحرية', icon: 'seaweed' },
        { id: 'green-notes', label: 'Green Notes', labelAr: 'نوتات خضراء', icon: 'green-notes' },
        { id: 'laurel', label: 'Laurel', labelAr: 'غار', icon: 'laurel' },
        { id: 'fig-leaf', label: 'Fig Leaf', labelAr: 'ورق التين', icon: 'fig-leaf' },
        { id: 'moss', label: 'Moss', labelAr: 'طحلب', icon: 'moss' },
        { id: 'black-tea', label: 'Black Tea', labelAr: 'شاي أسود', icon: 'black-tea' },
        { id: 'davana', label: 'Davana', labelAr: 'دافانا', icon: 'davana' },
        { id: 'carrot-seeds', label: 'Carrot Seeds', labelAr: 'بذور الجزر', icon: 'carrot-seeds' },
        { id: 'absinthe', label: 'Absinthe', labelAr: 'أفسنتين', icon: 'absinthe' },
        { id: 'cassis', label: 'Cassis (Black Currant Leaf)', labelAr: 'ورق الكشمش', icon: 'cassis' },
    ],
    fruity: [
        { id: 'apple', label: 'Apple', labelAr: 'تفاح', icon: 'apple' },
        { id: 'pear', label: 'Pear', labelAr: 'كمثرى', icon: 'pear' },
        { id: 'peach', label: 'Peach', labelAr: 'خوخ', icon: 'peach' },
        { id: 'raspberry', label: 'Raspberry', labelAr: 'توت العليق', icon: 'raspberry' },
        { id: 'blackberry', label: 'Blackberry', labelAr: 'توت أسود', icon: 'blackberry' },
        { id: 'blackcurrant', label: 'Black Currant', labelAr: 'كشمش أسود', icon: 'blackcurrant' },
        { id: 'passion-fruit', label: 'Passionfruit', labelAr: 'فاكهة العاطفة', icon: 'passionfruit' },
        { id: 'plum', label: 'Plum', labelAr: 'برقوق', icon: 'plum' },
        { id: 'apricot', label: 'Apricot', labelAr: 'مشمش', icon: 'apricot' },
        { id: 'mango', label: 'Mango', labelAr: 'مانجو', icon: 'mango' },
        { id: 'pineapple', label: 'Pineapple', labelAr: 'أناناس', icon: 'pineapple' },
        { id: 'coconut', label: 'Coconut', labelAr: 'جوز الهند', icon: 'coconut' },
        { id: 'melon', label: 'Melon', labelAr: 'شمام', icon: 'melon' },
        { id: 'kiwi', label: 'Kiwi', labelAr: 'كيوي', icon: 'kiwi' },
        { id: 'lychee', label: 'Lychee', labelAr: 'ليتشي', icon: 'lychee' },
        { id: 'red-fruits', label: 'Red Fruits', labelAr: 'فواكه حمراء', icon: 'red-fruits' },
        { id: 'black-raspberry', label: 'Black Raspberry', labelAr: 'توت العليق الأسود', icon: 'raspberry' },
        { id: 'fig', label: 'Fig', labelAr: 'تين', icon: 'fig' },
        { id: 'banana', label: 'Banana', labelAr: 'موز', icon: 'banana' },
        { id: 'morello-cherry', label: 'Morello Cherry', labelAr: 'كرز موريلو', icon: 'cherry' },
        { id: 'wild-strawberry', label: 'Wild Strawberry', labelAr: 'فراولة برية', icon: 'strawberry' },
        { id: 'strawberry', label: 'Strawberry', labelAr: 'فراولة', icon: 'strawberry' },
        { id: 'red-apple', label: 'Red Apple', labelAr: 'تفاح أحمر', icon: 'apple' },
        { id: 'cherry', label: 'Cherry', labelAr: 'كرز', icon: 'cherry' },
        { id: 'rhubarb', label: 'Rhubarb', labelAr: 'راوند', icon: 'rhubarb' },
        { id: 'date', label: 'Dates', labelAr: 'تمر', icon: 'date' },
    ],
    middleEastern: [
        { id: 'oud', label: 'Oud', labelAr: 'عود', icon: 'oud' },
        { id: 'damask-rose', label: 'Damask Rose', labelAr: 'ورد دمشقي', icon: 'rose' },
        { id: 'taif-rose', label: 'Taif Rose', labelAr: 'ورد الطائف', icon: 'rose' },
        { id: 'bakhoor', label: 'Bakhoor', labelAr: 'بخور', icon: 'incense' },
        { id: 'agarwood', label: 'Agarwood', labelAr: 'أغاروود', icon: 'oud' },
    ],
};

// Note categories for the quiz UI
export const noteCategories = [
    { id: 'freshCitrus', label: 'Fresh & Citrus', labelAr: 'منعش وحمضيات', icon: 'citrus', description: '27 notes' },
    { id: 'floral', label: 'Floral', labelAr: 'زهري', icon: 'floral', description: '33 notes' },
    { id: 'sweetGourmand', label: 'Sweet & Gourmand', labelAr: 'حلو', icon: 'gourmand', description: '32 notes' },
    { id: 'woody', label: 'Woody', labelAr: 'خشبي', icon: 'woody', description: '14 notes' },
    { id: 'spicy', label: 'Spicy', labelAr: 'حار', icon: 'spicy', description: '16 notes' },
    { id: 'amberyResinous', label: 'Ambery & Resinous', labelAr: 'عنبري', icon: 'ambery', description: '15 notes' },
    { id: 'musky', label: 'Musky', labelAr: 'مسكي', icon: 'musky', description: '5 notes' },
    { id: 'leatherSmoky', label: 'Leather & Smoky', labelAr: 'جلد ودخان', icon: 'leathery', description: '8 notes' },
    { id: 'earthyGreen', label: 'Earthy & Green', labelAr: 'ترابي وأخضر', icon: 'earthy', description: '17 notes' },
    { id: 'fruity', label: 'Fruity', labelAr: 'فاكهي', icon: 'fruity', description: '26 notes' },
    { id: 'middleEastern', label: 'Middle Eastern', labelAr: 'شرقي', icon: 'eastern', description: '5 notes' },
];

// Get all notes as a flat array
export const allNotes = Object.values(fragranceNotes).flat();

export const uniqueAllNotes = Array.from(
    new Map(allNotes.map(note => [note.id, note])).values()
);

// Popular notes for quick selection (most common preferences)
export const popularNotes = [
    { id: 'vanilla', label: 'Vanilla', labelAr: 'فانيليا', icon: 'vanilla' },
    { id: 'rose', label: 'Rose', labelAr: 'ورد', icon: 'rose' },
    { id: 'oud', label: 'Oud', labelAr: 'عود', icon: 'oud' },
    { id: 'jasmine', label: 'Jasmine', labelAr: 'ياسمين', icon: 'jasmine' },
    { id: 'sandalwood', label: 'Sandalwood', labelAr: 'صندل', icon: 'sandalwood' },
    { id: 'bergamot', label: 'Bergamot', labelAr: 'برغموت', icon: 'bergamot' },
    { id: 'musk', label: 'Musk', labelAr: 'مسك', icon: 'musk' },
    { id: 'amber', label: 'Amber', labelAr: 'عنبر', icon: 'amber' },
    { id: 'coffee', label: 'Coffee', labelAr: 'قهوة', icon: 'coffee' },
    { id: 'lavender', label: 'Lavender', labelAr: 'لافندر', icon: 'lavender' },
    { id: 'tobacco', label: 'Tobacco', labelAr: 'تبغ', icon: 'tobacco' },
    { id: 'leather', label: 'Leather', labelAr: 'جلد', icon: 'leather' },
];

// Notes commonly avoided
export const commonlyAvoidedNotes = [
    { id: 'oud', label: 'Heavy Oud', labelAr: 'عود ثقيل', icon: 'oud' },
    { id: 'rose', label: 'Strong Rose', labelAr: 'ورد قوي', icon: 'rose' },
    { id: 'vanilla', label: 'Heavy Vanilla', labelAr: 'فانيليا ثقيلة', icon: 'vanilla' },
    { id: 'musk', label: 'Strong Musk', labelAr: 'مسك قوي', icon: 'musk' },
    { id: 'tobacco', label: 'Tobacco', labelAr: 'تبغ', icon: 'tobacco' },
    { id: 'patchouli', label: 'Patchouli', labelAr: 'باتشولي', icon: 'patchouli' },
    { id: 'leather', label: 'Leather', labelAr: 'جلد', icon: 'leather' },
    { id: 'smoke', label: 'Smoke', labelAr: 'دخان', icon: 'smoke' },
    { id: 'incense', label: 'Incense', labelAr: 'بخور', icon: 'incense' },
    { id: 'animalic', label: 'Animalic Notes', labelAr: 'روائح حيوانية', icon: 'leather' },
    { id: 'powdery', label: 'Powdery Notes', labelAr: 'روائح بودرية', icon: 'white-musk' },
    { id: 'aquatic', label: 'Aquatic/Marine', labelAr: 'مائي/بحري', icon: 'wave' },
    { id: 'none', label: "I'm open to anything!", labelAr: 'منفتح على كل شيء', icon: 'check' },
];

export const quizSteps: QuizStep[] = [
    {
        id: 1,
        name: 'gender',
        question: "Who is this fragrance for?",
        questionAr: "لمن هذا العطر؟",
        type: 'single',
        required: true,
        skippable: false,
        options: [
            { id: 'female', label: 'For Her', labelAr: 'للنساء', icon: 'female' },
            { id: 'male', label: 'For Him', labelAr: 'للرجال', icon: 'male' },
            { id: 'unisex', label: 'Unisex', labelAr: 'للجنسين', icon: 'unisex' }
        ]
    },
    {
        id: 2,
        name: 'favoriteNotes',
        question: "Which notes do you love?",
        questionAr: "ما النوتات التي تحبها؟",
        type: 'multiple',
        required: false,
        skippable: true,
        options: [
            { id: 'none', label: "No specific notes", labelAr: 'لا يوجد', icon: 'check' },
            ...uniqueAllNotes
        ]
    },
    {
        id: 3,
        name: 'avoidedNotes',
        question: "Any notes you avoid?",
        questionAr: "هل هناك نوتات تريد تجنبها؟",
        type: 'multiple',
        required: false,
        skippable: true,
        options: [
            { id: 'none', label: "I'm open to anything!", labelAr: 'منفتح على كل شيء', icon: 'check' },
            ...uniqueAllNotes
        ]
    },
    {
        id: 4,
        name: 'season',
        question: "When will you mostly wear this?",
        questionAr: "متى سترتدي هذا العطر؟",
        type: 'single',
        required: true,
        skippable: false,
        options: [
            { id: 'spring', label: 'Spring', labelAr: 'الربيع', icon: 'spring', description: 'Light & fresh' },
            { id: 'summer', label: 'Summer', labelAr: 'الصيف', icon: 'summer', description: 'Citrus & aquatic' },
            { id: 'fall', label: 'Fall', labelAr: 'الخريف', icon: 'fall', description: 'Warm & spicy' },
            { id: 'winter', label: 'Winter', labelAr: 'الشتاء', icon: 'winter', description: 'Rich & cozy' },
            { id: 'all', label: 'All Year', labelAr: 'طوال السنة', icon: 'calendar', description: 'Versatile' }
        ]
    },
    {
        id: 5,
        name: 'intensity',
        question: "How strong do you like your fragrance?",
        questionAr: "ما مدى قوة العطر؟",
        type: 'single',
        required: true,
        skippable: false,
        options: [
            { id: 'light', label: 'Light & Subtle', labelAr: 'خفيف', icon: 'light', description: 'Close to skin' },
            { id: 'moderate', label: 'Moderate', labelAr: 'معتدل', icon: 'moderate', description: 'Balanced' },
            { id: 'strong', label: 'Bold & Powerful', labelAr: 'قوي', icon: 'strong', description: 'Statement maker' }
        ]
    }
];
